// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/05/2024, 10:34:13 pm


// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/05/2024, 10:34:13 pm
const configMerger = require("C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {
  "content": [],
  "theme": {
    "extend": {
      keyframes: {
        scale: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.5)' },
        },
        fade: {
          '0%, 100%': { opacity: 0.5 },
          '50%': { opacity: 1 },
        }
      },
      animation: {
        'scale-up-down': 'scale 2s infinite',
        'fade-in-out': 'fade 2s infinite',
      }
    }
  },
  "plugins": []
};

const config = [].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { 
  content: [
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/components/**/*.{vue,js,jsx,mjs,ts,tsx}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/pages/**/*.{vue,js,jsx,mjs,ts,tsx}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/plugins/**/*.{js,ts,mjs}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/composables/**/*.{js,ts,mjs}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/utils/**/*.{js,ts,mjs}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}",
    "C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/app.config.{js,ts,mjs}"
  ]
}));

module.exports = config;


  






// const configMerger = require("C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

// const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

// const config = [

// ]
// .reduce((prev, curr) => 
    // configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/plugins/**/*.{js,ts,mjs}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/composables/**/*.{js,ts,mjs}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/utils/**/*.{js,ts,mjs}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/OneDrive/Desktop/ZTM/ChatBot/jarvis/app.config.{js,ts,mjs}"] }));

// module.exports = config